CREATE TABLE TB_USER (
    ID_USER INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN_USER varchar(255),
    PASS_USER varchar(255)
);

CREATE TABLE TB_MUSICIAN (
    ID_MUSICIAN INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME_MUSICIAN varchar(255),
    ARTISTICNM_MUSICIAN varchar(255),
    CPF_MUSICIAN varchar(255),
    INSTRUMENT_MUSICIAN varchar(255),
    DESCRIPTION_MUSICIAN varchar(255),
);